### ISSUE TITLE
Mejorar documentacion de integracion con keycloak

### ISSUE THREAD

**Issue by Giorgiosaud** [modyo/modyo-docs#540]
en el caso de los callbacks cambiaron los callback urls ahora debe incluir el reino de modyo

**Comment by DGarzaLee** [comment]
En [Identity Providers | Keycloak ](https://docs.modyo.com/es/platform/core/integrations/identity-providers.html#keycloak)

El paso 4 incluye los realms:
4. Configura las **Valid Redirect URIs** con las URLs de callback y logout de la cuenta Modyo, usando las URLs a la cuenta, agregando `/realms/mi-realm` en caso de estar usando uno. Por ejemplo: `test.modyo.com/realms/mi-realm/auth/openidc/callback` y `test.modyo.com/realms/mi-realm/logout*`.
